### ISSUE TITLE
Input data and start script

### ISSUE THREAD

**Issue by smshuai** [vanallenlab/retained-intron-neoantigen-pipeline#1]
Hi Claire,

I'm wondering what's the required input data for your pipeline? I have RNA-Seq FASTQ as well as STAR-aligned BAM. Which should I use?

My second question is that I saw multiple wrapper scripts, i.e., `overallPipelineWrapper.sh`, `getNeoantigenBinders.sh` and `getNeoantigenBinders_KMAKallisto.sh`. I'm wondering what's the difference between them and which one might be the best for me to use?

Best regards,
Shimin

**Comment by ClaireMargolis** [comment]
Hi Shimin, 

The input file for my pipeline is the output file from the KMA package (on GitHub, referenced in the README). The overall flow is RNA-Seq FASTQ > Expression quantification (KMA is built to work with either eXpress or kallisto) > KMA > custom pipeline. KMA has additional documentation on how to quantify expression for this context (i.e., including retained intron transcripts). 

In terms of the scripts, the version that I used in the publication is `getNeoantigenBinders_KMAKallisto.sh`, which is specifically designed to work using kallisto as the pseudoalignment and quantification algorithm. `getNeoantigenBinders.sh` is completely analogous except that it assumes eXpress was the algorithm used in the prior step.
