### ISSUE TITLE
Questions about the kma file

### ISSUE THREAD

**Issue by kevin199011** [vanallenlab/retained-intron-neoantigen-pipeline#2]
Hi, I'm a bit confused of the kma file that is needed for the input.
Is the kma file used here from newIntronRetention function? Also, do you perform the filtering steps as in the kma documentation?
It would be great that you can have some sample file for reference.

Also, I didn't see the kma kallisto version on the KMA documentation, is this a customized code?

Thank you!

Kevin

**Comment by edkonyakhina** [comment]
Hello!
I would also like to use kma-kallisto version. Could you say how did you make KMA-post-processing in this case?

Jenya

**Comment by MySelvan** [comment]
Hi,
I would also like to use kma-kallisto version and would appreciate information on how to perform KMA-post-processing using kallisto files which will then be used the input for the pipeline.

Thanks,
My

**Comment by ClaireMargolis** [comment]
Hi all -- 
Sorry for the delayed response. The KMA repository has been updated to include the KMA-kallisto updated package, available at this link: https://github.com/pachterlab/kma/blob/master/inst/kma-kallisto.zip. Also included a note in the readme to this extent. Thanks!
